remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Name of website
title: Eoin McDoonnell's blog

# Your name to show in the footer
author: Eoin McDonnell


plugins:
  - jekyll-paginate
  - jekyll-sitemap


# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM